apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: nintendo-suggest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40   # 40%超えたらスケールアップ
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15     # 15秒で即スケールアップ
      policies:
        - type: Pods
          value: 10                        # 一度に最大10台追加
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30     # 負荷が落ちてから30秒後にスケールダウン
      policies:
        - type: Pods
          value: 10
          periodSeconds: 15              # 15秒ごとに最大2台削除
