apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: nintendo-suggest
type: Opaque
stringData:
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_ROOT_PASSWORD: "rootpassword"
  DB_NAME: "nintendo_suggest"
